Milestone #1: Build Cryptocurrency Exchange Rate App
Anjacodes/Daily_Crypto_Stats pull request #1
Opened 2022-02-02 19:42 UTC by Anjacodes

In this milestone, I: 

* Used the Coinlore Live API for fetching data on current cryptocurrency exchange rates
* Built files structure for your React app and prepared routes and navigation.
* Made sure that a user can display a list of cryptocurrencies and filter them.
* Created the tests for the application.
* Styled the components to match the design provided.
* Deployed the project and tested for final details.
* Recorded a video.
* Created a good README.

[Link to project video on Loom](https://www.loom.com/share/ef165aafac2e442c9717af83e03473bd)

[Link to Live Demo](https://inspiring-johnson-ba0a03.netlify.app/)

2022-02-02 20:44 UTC, omar-labana requested changes
Hi @Anjacodes, 

Excellent work so far! 👌
You have implemented almost all the required features correctly and without any errors. ✔️ 
Very nice touch on styling using Tailwind CSS and adding a fall back route for the routes the don't exist.
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
- [ ] After implementing the filter component, kindly record covering the new feature along with a  highlight about a piece of the code the you find interesting or proud of making.

> _Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-02 20:44 UTC, omar-labana commented on public/index.html
> +      </style>
- [ ] _[OPTIONAL]_ Please move these imports to the index.css file instead of adding two style tags.

2022-02-02 20:44 UTC, omar-labana commented on src/components/Main/Main.js
> +  const content = coins.map((coin) => (<Link to={`/details/${coin.id}`} key={coin.id}><Coin coin={coin} /></Link>));
- [ ] One of the project requirements is to implement a filter stateless component to filter data retrieved from the API, this should be done using a controlled component(search input). The list of items shown should be the result of filtering through the coins.

2022-02-02 20:44 UTC, omar-labana commented on README.md
> +Thank you Microverse for your guidance in making a great portfolio for myself! -->
- [ ] The README should contain an "Acknowledgements" section or similar that gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2022-02-03 14:32 UTC, dasileker approved these changes
## **Hi @Anjacodes,** 

## **Congratulations! 🎉 Project Approved ✅**
Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 
 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-03 14:56 UTC, merged